markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl:

# Title of the Site
title: David W. Miller
# Description of the Site
description: Sim's Lab
# URL of Image of the Site
site-image: https://david-miller.life/images/banner.png
# Keywords of the Site
site-keywords: Unreal Developer, Halon Entertainment, NASA, Johnson Space Center
# URL for the Image of custom Favicon
favicon-url: 'https://david-miller.life/images/favicon.ico'

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://david-miller.life/images/LS_Film_Interior.jpeg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: simsaladoo@hotmail.com
facebook_username: simsaladoo
twitter_username: simsaladoo
instagram_username: simsaladoo
linkedin_username: simsaladoo
github_username:  Simsaladoo
youtube_channel_id: UCKc9LeuyYEmf89ZrEE3ilfw
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: G-FV79JWVKLW

# Disqus
disqus-shortname: simsaladoo

# Name of the Author
author-name: Simsaladoo
# URL for the Image of the Author
author-image: https://david-miller.life/images/hawaii.png
# 60 Words About the Author
author-about: I'm David, an Unreal Engine developer and Technical Artist with a background in pipeline tools. I've worked the last 9 years in the entertainment industry on films, commercials, video game trailers and teasers, and VR games. C# was my gateway into programming during my time at NASA, and the diverse projects I've working on have given me a wealth of experience and perspective. Optimization, translating data, shadow-catching mattes, post-process shaders, and on-the-spot tool creation.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/Simsaladoo

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
